### ISSUE TITLE
Invalid .scsslintrc file? should be .sass-lint.yml

### ISSUE THREAD

**Issue by seperez** [mercadolibre/css-style-guide#29]
Por lo que pude ver en la documentación del módulo [gulp-sass-lint](https://www.npmjs.com/package/gulp-sass-lint), se usa el file **.sass-lint.yml**, no encuntro registro alguno en la web acerca del .scsslintrc. Cuando armamos el scaffolding lo agregue pero claramente no verifique que sea correcto. 

Esto trae un problema que es que el linter no esta tomando la configuración personalizada sino que usa una por defecto.

Ademas el plugin de linteo de Atom tambien falla, y pide el yml. 

Yo ya lo tengo armado en un proyecto, puedo mandar el PR para actualizar este repo para que gulp-tasks se nutra del archivo correcto.

**Comment by seperez** [comment]
@atma @jvnni @pazguille @llinares @josepapaianni @sleopardo

**Comment by seperez** [comment]
Este es el ejemplo:

https://github.com/mercadolibre/fury_buyingflow-cart/blob/develop/ui-app/.sass-lint.yml

**Comment by battaglr** [comment]
@seperez, esto lo arregló @jvnni hoy en el PR #27. Está faltando generar el PR a *gulp_tasks*; dejo abierto el issue hasta que eso pase.

**Comment by seperez** [comment]
@battaglr Ah joya. No lo veo en master por eso levante el issue. Quien se encarga de hacer la release?

**Comment by pazguille** [comment]
@seperez Creo que se puede usar siempre y cuando se indique en las options como config. Nose si tiene mucho sentido.

```
scsslint: {
  options: {
    config: '.scsslintrc'
  },
},
```

**Comment by battaglr** [comment]
@seperez, yo ahora genero un nuevo release y si querés podés cerrar la parte que falta de *gulp_tasks*. 😉

@pazguille, está bueno saberlo; de todas formas, opino igual que vos, no creo que tenga mucho sentido modificar el nombre del file; fue una confusión al migrar de un linter a otro.

**Comment by seperez** [comment]
@pazguille si vi esa config, pero de todas formas en atom y en intelij no se puede configurar a menos que sea un yml y me parece importante que los IDEs/Editores puedan levantar esta config ya que es mas agíl corregir posibles errores en el momento en que se esta programando.

**Comment by pazguille** [comment]
@seperez Si, estoy de acuerdo. Por eso me parece que no tiene mucho sentido usar el scsslintrc, cuando conel yml, anda de una.

**Comment by battaglr** [comment]
Closed by #30.
