### ISSUE TITLE
Modify `allow-single-line` value

### ISSUE THREAD

**Issue by battaglr** [mercadolibre/css-style-guide#32]
The rule `allow-single-line` must be set on `true` instead of [`false`](https://github.com/mercadolibre/css-style-guide/blob/master/.sass-lint.yml#L19), since [our style guide allows this format](https://github.com/mercadolibre/css-style-guide#rules).

👋  @jvnni, @pmontesano, are you okay with this?

**Comment by pmontesano** [comment]
@battaglr esta ok para mi!

**Comment by battaglr** [comment]
Resolved by 614136129025c6676708d41fd4fbcf54ae835e94.
